# Imports

In [1]:
import pandas as pd
import numpy as np

# Load Data

In [9]:
# Load lecture CSV file, set the proper index and remove dummy index
nutrition = pd.read_csv('../data/nutrition.csv', index_col='name')
nutrition.drop('Unnamed: 0', axis=1, inplace=True)

# convert to float
nutrition = nutrition.replace(to_replace='[a-zA-Z]', value='', regex=True)
nutrition = nutrition.astype(float)

nutrition.head()

,serving_size,calories,total_fat,saturated_fat,cholesterol,sodium,choline,folate,folic_acid,niacin,...,fat,saturated_fatty_acids,monounsaturated_fatty_acids,polyunsaturated_fatty_acids,fatty_acids_total_trans,alcohol,ash,caffeine,theobromine,water
name,,,,,,,,,,,,,,,,,,,,,
Cornstarch,100.0,381.0,0.1,NaN,0.0,9.0,0.4,0.0,0.0,0.000,...,0.05,0.009,0.016,0.025,0.0,0.0,0.09,0.0,0.0,8.32
"Nuts, pecans",100.0,691.0,72.0,6.2,0.0,0.0,40.5,22.0,0.0,1.167,...,71.97,6.180,40.801,21.614,0.0,0.0,1.49,0.0,0.0,3.52
"Eggplant, raw",100.0,25.0,0.2,NaN,0.0,2.0,6.9,22.0,0.0,0.649,...,0.18,0.034,0.016,0.076,0.0,0.0,0.66,0.0,0.0,92.30
"Teff, uncooked",100.0,367.0,2.4,0.4,0.0,12.0,13.1,0.0,0.0,3.363,...,2.38,0.449,0.589,1.071,0.0,0.0,2.37,0.0,0.0,8.82
"Sherbet, orange",100.0,144.0,2.0,1.2,1.0,46.0,7.7,4.0,0.0,0.063,...,2.00,1.160,0.530,0.080,1.0,0.0,0.40,0.0,0.0,66.10

## Filtering in 2D

In [10]:
nutrition.shape

(8789, 75)

In [11]:
# 'like' parameter is CASE SENSITIVE
nutrition.filter(axis=0, like='Octopus')

,serving_size,calories,total_fat,saturated_fat,cholesterol,sodium,choline,folate,folic_acid,niacin,...,fat,saturated_fatty_acids,monounsaturated_fatty_acids,polyunsaturated_fatty_acids,fatty_acids_total_trans,alcohol,ash,caffeine,theobromine,water
name,,,,,,,,,,,,,,,,,,,,,
Octopus (Alaska Native),100.0,56.0,0.8,0.2,41.0,0.0,0.0,0.0,0.0,2.0,...,0.8,0.2,0.0,0.2,41.0,0.0,1.5,0.0,0.0,84.0

In [12]:
nutrition.filter(axis=0, like='octopus')

,serving_size,calories,total_fat,saturated_fat,cholesterol,sodium,choline,folate,folic_acid,niacin,...,fat,saturated_fatty_acids,monounsaturated_fatty_acids,polyunsaturated_fatty_acids,fatty_acids_total_trans,alcohol,ash,caffeine,theobromine,water
name,,,,,,,,,,,,,,,,,,,,,
"Mollusks, raw, common, octopus",100.0,82.0,1.0,0.2,48.0,230.0,65.0,16.0,0.0,2.10,...,1.04,0.227,0.162,0.239,48.0,0.0,1.6,0.0,0.0,80.25
"Mollusks, moist heat, cooked, common, octopus",100.0,164.0,2.1,0.5,96.0,460.0,81.0,24.0,0.0,3.78,...,2.08,0.453,0.324,0.477,96.0,0.0,3.2,0.0,0.0,60.50

In [13]:
# regex parameter allows for modifiers to check case insensitive values
nutrition.filter(axis=0, regex='(?i)octOPUS')

,serving_size,calories,total_fat,saturated_fat,cholesterol,sodium,choline,folate,folic_acid,niacin,...,fat,saturated_fatty_acids,monounsaturated_fatty_acids,polyunsaturated_fatty_acids,fatty_acids_total_trans,alcohol,ash,caffeine,theobromine,water
name,,,,,,,,,,,,,,,,,,,,,
Octopus (Alaska Native),100.0,56.0,0.8,0.2,41.0,0.0,0.0,0.0,0.0,2.00,...,0.80,0.200,0.000,0.200,41.0,0.0,1.5,0.0,0.0,84.00
"Mollusks, raw, common, octopus",100.0,82.0,1.0,0.2,48.0,230.0,65.0,16.0,0.0,2.10,...,1.04,0.227,0.162,0.239,48.0,0.0,1.6,0.0,0.0,80.25
"Mollusks, moist heat, cooked, common, octopus",100.0,164.0,2.1,0.5,96.0,460.0,81.0,24.0,0.0,3.78,...,2.08,0.453,0.324,0.477,96.0,0.0,3.2,0.0,0.0,60.50

In [14]:
# filter methods can be chained
(
    nutrition
    .filter(axis=0, regex='(?i)octOPUS')
    .filter(axis=1, regex='(?i)cholesterol')
)

                                               cholesterol
name
Octopus (Alaska Native)                               41.0
Mollusks, raw, common, octopus                        48.0
Mollusks, moist heat, cooked, common, octopus         96.0

In [15]:
# you can also supply a list of items to be filtered instead of like/regex
(
    nutrition
    .filter(axis=0, regex='(?i)octOPUS')
    .filter(axis=1, items=['calories', 'sodium', 'niacin'])
)

                                               calories  sodium  niacin
name
Octopus (Alaska Native)                            56.0     0.0    2.00
Mollusks, raw, common, octopus                     82.0   230.0    2.10
Mollusks, moist heat, cooked, common, octopus     164.0   460.0    3.78

## Sorting the Dataframe

In [17]:
# Any Series can be sorted
nutrition.saturated_fat.sort_values()

name
Rice, cooked, enriched, short-grain, white                                                               0.1
Squash, without salt, drained, boiled, cooked, includes skin, zucchini, summer                           0.1
Peas, drained solids, no salt added, canned, green                                                       0.1
Yogurt, nonfat, fruit variety                                                                            0.1
Squash, with salt, drained, boiled, cooked, crookneck and straightneck, summer                           0.1
                                                                                                        ...
Beverages, prepared with water, frozen concentrate, with juice and pulp, breakfast type, Orange drink    NaN
Apple juice, diluted with 3 volume water without added ascorbic acid, unsweetened, frozen concentrate    NaN
Carbonated beverage, without caffeine, with sodium saccharin, other than cola or pepper, low calorie     NaN
Apple juice, with added ascorbic acid, diluted with 3 volume water, unsweetened, frozen concentrate      NaN
Pan Dulce, contains wheat flour and rice flour, cookie-like, Salpora de Arroz con Azucar, LA RICURA      NaN
Name: saturated_fat, Length: 8789, dtype: float64

In [19]:
nutrition.sort_values(by=['sodium'], ascending=False).head()

,serving_size,calories,total_fat,saturated_fat,cholesterol,sodium,choline,folate,folic_acid,niacin,...,fat,saturated_fatty_acids,monounsaturated_fatty_acids,polyunsaturated_fatty_acids,fatty_acids_total_trans,alcohol,ash,caffeine,theobromine,water
name,,,,,,,,,,,,,,,,,,,,,
"Salt, table",100.0,0.0,0.0,NaN,0.0,38758.0,0.0,0.0,0.0,0.000,...,0.00,0.000,0.000,0.000,0.0,0.0,99.8,0.0,0.0,0.20
"Leavening agents, baking soda",100.0,0.0,0.0,NaN,0.0,27360.0,0.0,0.0,0.0,0.000,...,0.00,0.000,0.000,0.000,0.0,0.0,36.9,0.0,0.0,0.20
"Desserts, unsweetened, tablets, rennin",100.0,84.0,0.1,NaN,0.0,26050.0,0.0,0.0,0.0,0.000,...,0.10,0.041,0.038,0.007,0.0,0.0,72.5,0.0,0.0,6.50
"Soup, dry, powder, beef broth or bouillon",100.0,213.0,8.9,4.3,10.0,26000.0,113.4,32.0,0.0,4.467,...,8.89,4.320,3.616,0.332,10.0,0.0,54.5,0.0,0.0,3.27
"Soup, dry, cubed, beef broth",100.0,170.0,4.0,2.0,4.0,24000.0,113.4,32.0,0.0,3.300,...,4.00,1.990,1.670,0.160,4.0,0.0,59.3,0.0,0.0,3.30

In [21]:
# Sort by multiple columns, and multiple orders
nutrition.sort_values(by=['cholesterol', 'sodium'], ascending=[False, True]).head()

,serving_size,calories,total_fat,saturated_fat,cholesterol,sodium,choline,folate,folic_acid,niacin,...,fat,saturated_fatty_acids,monounsaturated_fatty_acids,polyunsaturated_fatty_acids,fatty_acids_total_trans,alcohol,ash,caffeine,theobromine,water
name,,,,,,,,,,,,,,,,,,,,,
"Beef, simmered, cooked, brain, variety meats and by-products",100.0,151.0,11.0,2.4,3100.0,108.0,490.9,5.0,0.0,3.620,...,10.53,2.394,1.882,1.632,3100.0,0.0,1.46,0.0,0.0,74.86
"Veal, braised, cooked, brain, variety meats and by-products",100.0,136.0,9.6,2.2,3100.0,156.0,0.0,3.0,0.0,2.430,...,9.63,2.180,1.740,1.490,3100.0,0.0,1.40,0.0,0.0,76.89
"Beef, raw, brain, variety meats and by-products",100.0,143.0,10.0,2.3,3010.0,126.0,0.0,3.0,0.0,3.550,...,10.30,2.300,1.890,1.586,3010.0,0.0,1.51,0.0,0.0,76.29
"Lamb, soaked and fried, cooked, brains, imported, New Zealand",100.0,154.0,11.0,1.4,2559.0,101.0,0.0,0.0,0.0,2.995,...,10.92,1.365,4.168,0.999,2559.0,0.0,3.39,0.0,0.0,73.11
"Pork, braised, cooked, brain, variety meats and by-products, fresh",100.0,138.0,9.5,2.2,2552.0,91.0,0.0,4.0,0.0,3.330,...,9.51,2.150,1.720,1.470,2552.0,0.0,1.40,0.0,0.0,75.88

## .between() method for Series

In [23]:
nutrition.calories.head(10)

name
Cornstarch            381.0
Nuts, pecans          691.0
Eggplant, raw          25.0
Teff, uncooked        367.0
Sherbet, orange       144.0
Cauliflower, raw       25.0
Taro leaves, raw       42.0
Lamb, raw, ground     282.0
Cheese, camembert     300.0
Vegetarian fillets    290.0
Name: calories, dtype: float64

In [24]:
# The .between() method will return a boolean mask
nutrition.calories.between(20, 60)

name
Cornstarch                                                                                            False
Nuts, pecans                                                                                          False
Eggplant, raw                                                                                          True
Teff, uncooked                                                                                        False
Sherbet, orange                                                                                       False
                                                                                                      ...
Beef, raw, all grades, trimmed to 0" fat, separable lean and fat, boneless, top round roast, round    False
Lamb, cooked, separable lean only, composite of trimmed retail cuts, frozen, imported, New Zealand    False
Lamb, raw, separable lean and fat, composite of trimmed retail cuts, frozen, imported, New Zealand    False
Beef, raw, all grades, trimmed to 0" fat, separable lean only, boneless, eye of round roast, round    False
Beef, raw, all grades, trimmed to 0" fat, separable lean only, boneless, eye of round steak, round    False
Name: calories, Length: 8789, dtype: bool

In [30]:
# Same number of rows as the actual dataframe
nutrition.calories.between(20, 60).shape

(8789,)

In [32]:
nutrition[nutrition.calories.between(20, 60)].sample(5)

,serving_size,calories,total_fat,saturated_fat,cholesterol,sodium,choline,folate,folic_acid,niacin,...,fat,saturated_fatty_acids,monounsaturated_fatty_acids,polyunsaturated_fatty_acids,fatty_acids_total_trans,alcohol,ash,caffeine,theobromine,water
name,,,,,,,,,,,,,,,,,,,,,
"Peppers, solids and liquids, excluding seeds, pods, canned, green, hot chili",100.0,21.0,0.1,NaN,0.0,1173.0,6.8,10.0,0.0,0.800,...,0.10,0.010,0.006,0.055,0.0,0.0,1.40,0.0,0.0,92.50
"Borage, raw",100.0,21.0,0.7,0.2,0.0,80.0,0.0,13.0,0.0,0.900,...,0.70,0.170,0.211,0.109,0.0,0.0,1.44,0.0,0.0,93.00
"Mush, blue corn with ash (Navajo)",100.0,54.0,0.5,0.1,0.0,8.0,0.0,4.0,0.0,0.283,...,0.49,0.074,0.109,0.208,0.0,0.0,0.44,0.0,0.0,86.67
"Peppers, solids and liquids, excluding seeds, canned, red, hot chili",100.0,21.0,0.1,NaN,0.0,1173.0,6.8,10.0,0.0,0.800,...,0.10,0.010,0.006,0.055,0.0,0.0,1.40,0.0,0.0,92.50
"Cereals, without salt, stove-top, cooked with water, 2 1/2 minute cook time, CREAM OF WHEAT",100.0,56.0,0.2,0.1,0.0,34.0,0.0,29.0,15.0,0.803,...,0.20,0.051,0.030,0.102,0.0,0.0,0.42,0.0,0.0,86.20

## Min, Max, IdxMin, IdxMax

In [35]:
# What is the highest amount of potassium from the list?
nutrition.potassium.max()

16500.0

In [36]:
# And what food has the max amount of potassium?
nutrition.potassium.idxmax()

'Leavening agents, cream of tartar'

In [39]:
(
    nutrition
    .sort_values(by='potassium', ascending=False)
    .filter(axis=1, items=['potassium', 'sodium'])
    .head(5)
)

                                                    potassium  sodium
name
Leavening agents, cream of tartar                     16500.0    52.0
Leavening agents, low-sodium, baking powder           10100.0    90.0
Parsley, freeze-dried                                  6300.0   391.0
Beverages, unsweetened, decaffeinated, instant,...     6040.0    72.0
Beverages, powder, unsweetened, instant, tea           6040.0    72.0

In [40]:
# 'Good Foods' are the ones in which the Potassium/Sodium ratio is close to 16

nutrition['potassium_sodium_ratio'] = nutrition.potassium / nutrition.sodium

In [41]:
(
    nutrition
    .sort_values(by='potassium', ascending=False)
    .filter(axis=1, items=['potassium', 'sodium', 'potassium_sodium_ratio'])
    .head(5)
)

,potassium,sodium,potassium_sodium_ratio
name,,,
"Leavening agents, cream of tartar",16500.0,52.0,317.307692
"Leavening agents, low-sodium, baking powder",10100.0,90.0,112.222222
"Parsley, freeze-dried",6300.0,391.0,16.112532
"Beverages, unsweetened, decaffeinated, instant, tea",6040.0,72.0,83.888889
"Beverages, powder, unsweetened, instant, tea",6040.0,72.0,83.888889

In [46]:
(
    nutrition[nutrition.potassium_sodium_ratio.between(15, 17)]
    .sort_values(by='potassium', ascending=False)
    .filter(axis=1, items=['potassium', 'sodium', 'potassium_sodium_ratio'])
)

,potassium,sodium,potassium_sodium_ratio
name,,,
"Parsley, freeze-dried",6300.0,391.0,16.112532
"Spices, dried, dill weed",3308.0,208.0,15.903846
"Peppers, freeze-dried, green, sweet",3170.0,193.0,16.424870
"Peppers, freeze-dried, red, sweet",3170.0,193.0,16.424870
"Winged bean tuber, raw",586.0,35.0,16.742857
"Fish, raw, wild, rainbow, trout",481.0,31.0,15.516129
"Spearmint, fresh",458.0,30.0,15.266667
"Tomato products, without salt added, puree, canned",439.0,28.0,15.678571
"Cereals ready-to-eat, ALPEN",418.0,27.0,15.481481
"Brussels sprouts, raw",389.0,25.0,15.560000
"Kohlrabi, without salt, drained, boiled, cooked",340.0,21.0,16.190476
"Nuts, canned, flaked, sweetened, dried (desiccated), coconut meat",324.0,20.0,16.200000
"Brussels sprouts, without salt, drained, boiled, cooked",317.0,21.0,15.095238
"Abiyuch, raw",304.0,20.0,15.200000
"Melons, raw, cantaloupe",267.0,16.0,16.687500
"Tofu, prepared with calcium sulfate, firm, raw",237.0,14.0,16.928571
"Asparagus, drained, boiled, cooked",224.0,14.0,16.000000
"Nuts, canned (liquid expressed from grated meat and water), coconut milk",220.0,13.0,16.923077
"Tomatoes, raw, green",204.0,13.0,15.692308
"Finger snacks, apple and cinnamon, GERBER GRADUATE PUFFS",196.0,13.0,15.076923
"Sapodilla, raw",193.0,12.0,16.083333
"Turnip greens, unprepared, frozen",184.0,12.0,15.333333
Poi,183.0,12.0,15.250000
"Fruit juice smoothie, GREEN GOODNESS, BOLTHOUSE FARMS",177.0,11.0,16.090909
"Beverages, prepared with water, frozen concentrate, with juice and pulp, breakfast type, Orange drink",167.0,10.0,16.700000
"Couscous, dry",166.0,10.0,16.600000
Vanilla extract,148.0,9.0,16.444444
"Babyfood, pear, juice",130.0,8.0,16.250000
"Beverages, high vitamin C, greater than 3% juice, fruit juice drink",122.0,8.0,15.250000
"Tofu, prepared with calcium sulfate and magnesium chloride (nigari), soft",120.0,8.0,15.000000
"Peaches, drained, heavy syrup, canned",94.0,6.0,15.666667
"Babyfood, peas and brown rice",93.0,6.0,15.500000
"Peaches, solids and liquids, heavy syrup pack, canned",92.0,6.0,15.333333
"Fruit cocktail, drained, heavy syrup, canned",90.0,6.0,15.000000
"Fruit salad, solids and liquids, extra heavy syrup, canned, (peach and pear and apricot and pineapple and cherry)",80.0,5.0,16.000000
"Babyfood, strained, papaya and applesauce with tapioca, fruit",79.0,5.0,15.800000
"Babyfood, mango with tapioca, fruit dessert",66.0,4.0,16.500000
"Pasta, ANCIENT HARVEST, cooked, corn flour and quinoa flour, gluten-free",63.0,4.0,15.750000
"Alcoholic beverages, higher alcohol, beer",62.0,4.0,15.500000
"Rice, UNCLE BENS, cooked, parboiled, brown",61.0,4.0,15.250000
"Babyfood, junior, with applesauce and bananas, oatmeal, cereal",48.0,3.0,16.000000
"Babyfood, strained, with applesauce and bananas, oatmeal, cereal",47.0,3.0,15.666667
"Beverages, canned, pineapple and orange juice drink",46.0,3.0,15.333333
"Margarine-like, without salt, stick/tub/bottle, 60% fat, vegetable oil spread",30.0,2.0,15.000000
"Margarine-like, with added vitamin D, without salt, stick/tub/bottle, 60% fat, vegetable oil spread",30.0,2.0,15.000000

## .nlargest(), .nsmallest()

In [48]:
nutrition.nlargest(10, columns='calories')

,serving_size,calories,total_fat,saturated_fat,cholesterol,sodium,choline,folate,folic_acid,niacin,...,saturated_fatty_acids,monounsaturated_fatty_acids,polyunsaturated_fatty_acids,fatty_acids_total_trans,alcohol,ash,caffeine,theobromine,water,potassium_sodium_ratio
name,,,,,,,,,,,,,,,,,,,,,
"Fish oil, cod liver",100.0,902.0,100.0,23.0,570.0,0.0,0.0,0.0,0.0,0.0,...,22.608,46.711,22.541,570.0,0.0,0.0,0.0,0.0,0.0,NaN
"Fish oil, menhaden",100.0,902.0,100.0,30.0,521.0,0.0,0.0,0.0,0.0,0.0,...,30.427,26.694,34.197,521.0,0.0,0.0,0.0,0.0,0.0,NaN
"Fat, mutton tallow",100.0,902.0,100.0,47.0,102.0,0.0,79.8,0.0,0.0,0.0,...,47.300,40.600,7.800,102.0,0.0,0.0,0.0,0.0,0.0,NaN
"Fish oil, sardine",100.0,902.0,100.0,30.0,710.0,0.0,0.0,0.0,0.0,0.0,...,29.892,33.841,31.867,710.0,0.0,0.0,0.0,0.0,0.0,NaN
"Fish oil, herring",100.0,902.0,100.0,21.0,766.0,0.0,0.0,0.0,0.0,0.0,...,21.290,56.564,15.604,766.0,0.0,0.0,0.0,0.0,0.0,NaN
"Fish oil, salmon",100.0,902.0,100.0,20.0,485.0,0.0,0.0,0.0,0.0,0.0,...,19.872,29.037,40.324,485.0,0.0,0.0,0.0,0.0,0.0,NaN
"Fat, beef tallow",100.0,902.0,100.0,50.0,109.0,0.0,79.8,0.0,0.0,0.0,...,49.800,41.800,4.000,109.0,0.0,0.0,0.0,0.0,0.0,NaN
Lard,100.0,902.0,100.0,39.0,95.0,0.0,49.7,0.0,0.0,0.0,...,39.200,45.100,11.200,95.0,0.0,0.0,0.0,0.0,0.0,NaN
"Fish oil, fully hydrogenated, menhaden",100.0,902.0,100.0,96.0,500.0,0.0,0.0,0.0,0.0,0.0,...,95.600,0.000,0.000,500.0,0.0,0.0,0.0,0.0,0.0,NaN
"Fat, chicken",100.0,900.0,100.0,30.0,85.0,0.0,122.4,0.0,0.0,0.0,...,29.800,44.700,20.900,85.0,0.0,0.0,0.0,0.0,0.2,NaN

In [49]:
nutrition.nsmallest(10, columns='cholesterol')

,serving_size,calories,total_fat,saturated_fat,cholesterol,sodium,choline,folate,folic_acid,niacin,...,saturated_fatty_acids,monounsaturated_fatty_acids,polyunsaturated_fatty_acids,fatty_acids_total_trans,alcohol,ash,caffeine,theobromine,water,potassium_sodium_ratio
name,,,,,,,,,,,,,,,,,,,,,
Cornstarch,100.0,381.0,0.1,NaN,0.0,9.0,0.4,0.0,0.0,0.000,...,0.009,0.016,0.025,0.0,0.0,0.09,0.0,0.0,8.32,0.333333
"Nuts, pecans",100.0,691.0,72.0,6.2,0.0,0.0,40.5,22.0,0.0,1.167,...,6.180,40.801,21.614,0.0,0.0,1.49,0.0,0.0,3.52,inf
"Eggplant, raw",100.0,25.0,0.2,NaN,0.0,2.0,6.9,22.0,0.0,0.649,...,0.034,0.016,0.076,0.0,0.0,0.66,0.0,0.0,92.30,114.500000
"Teff, uncooked",100.0,367.0,2.4,0.4,0.0,12.0,13.1,0.0,0.0,3.363,...,0.449,0.589,1.071,0.0,0.0,2.37,0.0,0.0,8.82,35.583333
"Cauliflower, raw",100.0,25.0,0.3,0.1,0.0,30.0,44.3,57.0,0.0,0.507,...,0.130,0.034,0.031,0.0,0.0,0.76,0.0,0.0,92.07,9.966667
"Taro leaves, raw",100.0,42.0,0.7,0.2,0.0,3.0,12.8,126.0,0.0,1.513,...,0.151,0.060,0.307,0.0,0.0,1.92,0.0,0.0,85.66,216.000000
Vegetarian fillets,100.0,290.0,18.0,2.8,0.0,490.0,82.0,102.0,0.0,12.000,...,2.849,4.376,9.332,0.0,0.0,5.00,0.0,0.0,45.00,1.224490
"PACE, Picante Sauce",100.0,25.0,0.0,NaN,0.0,781.0,0.0,0.0,0.0,0.000,...,0.000,0.000,0.000,0.0,0.0,3.85,0.0,0.0,89.90,0.000000
"Goji berries, dried",100.0,349.0,0.4,NaN,0.0,298.0,0.0,0.0,0.0,0.000,...,0.000,0.000,0.000,0.0,0.0,0.78,0.0,0.0,7.50,0.000000
"Mango nectar, canned",100.0,51.0,0.1,NaN,0.0,5.0,1.5,7.0,0.0,0.080,...,0.014,0.022,0.011,0.0,0.0,0.08,0.0,0.0,86.63,4.800000

In [50]:
nutrition.folic_acid.nlargest(5)

name
Yeast extract spread                                             2993.0
Cereals ready-to-eat, CAP'N CRUNCH with CRUNCHBERRIES, QUAKER    1611.0
Cereals ready-to-eat, CAP'N CRUNCH, QUAKER                       1536.0
Cereals ready-to-eat, SWEET CRUNCH/QUISP, QUAKER                 1536.0
Cereals ready-to-eat, QUAKER CRUNCHY BRAN, QUAKER                1535.0
Name: folic_acid, dtype: float64

# Challenge

Find the 10 foods with most vitamin B12. What do they have in common?

In [57]:
nutrition.vitamin_b12.nlargest(10)

name
Mollusks, moist heat, cooked, mixed species, clam                                   98.89
Beef, boiled, cooked, variety meats and by-products liver, imported, New Zealand    96.00
Lamb, raw, liver, variety meats and by-products                                     90.05
Lamb, pan-fried, cooked, liver, variety meats and by-products                       85.70
Veal, braised, cooked, liver, variety meats and by-products                         84.60
Beef, raw, liver, variety meats and by-products, imported, New Zealand              84.50
Beef, pan-fried, cooked, liver, variety meats and by-products                       83.13
Lamb, braised, cooked, kidneys, variety meats and by-products                       78.90
Lamb, braised, cooked, liver, variety meats and by-products                         76.50
Veal, pan-fried, cooked, liver, variety meats and by-products                       72.50
Name: vitamin_b12, dtype: float64

Isolate the foods in the dataset which are based on eggplant. Which has the most sodium?

In [54]:
(
    nutrition
    .filter(axis=0, regex='(?i)eggplant')
    .sort_values(by='sodium', ascending=False)
).sodium

name
Eggplant, pickled                                  1674.0
Eggplant, with salt, drained, boiled, cooked        239.0
Eggplant, raw                                         2.0
Eggplant, without salt, drained, boiled, cooked       1.0
Name: sodium, dtype: float64

Provide a sample of 4 random rows and 2 random columns

In [56]:
(
    nutrition
    .sample(4)
    .sample(2, axis=1)
)

                                                    glycine  vitamin_e
name
Salad dressing, coleslaw                              0.000       3.08
Infant formula, with ARA and DHA, powder, GO AN...    0.000      10.30
Cranberry juice cocktail, frozen concentrate          0.000       0.00
Lamb, braised, cooked, choice, trimmed to 1/4" ...    1.393       0.16

Remove all food items with at least one NaN
How many records are impacted?

In [63]:
nutrition_nona = nutrition.dropna(how='any')

In [65]:
nutrition.shape[0] - nutrition_nona.shape[0]

1736

From the remaining records, isolate those with between 20 and 40mg of vitamin C. 

Of this list, which one is the least caloric?

In [67]:
(
    nutrition[nutrition.vitamin_c.between(20, 40)]
    .nsmallest(1, columns='calories')
    .filter(axis=1, items=['vitamin_c', 'calories'])
)

                                                    vitamin_c  calories
name
Beverages, fortified with vitamin C, diet, citr...       39.3       1.0